### ISSUE TITLE
Windows 10 - downloaded EXE, no action

### ISSUE THREAD

**Issue by shackrock** [Sheherezadhe/awair-uploader#13]
When I try to open the Windows setup, nothing happens (no setup opens). Anyone else experiencing this?

**Comment by Loopher** [comment]
I get the something similar.  I have a window open up with Loading.... at the top.  Checking the task manager, there is minimal CPU activity. I tried running as administrator as well, no dice.

**Comment by Loopher** [comment]
Ah, I got the PlanetWatch logon screen to load when I went to View => Force Reload which caused the window to reload.

**Comment by Loopher** [comment]
I got the tool to load and list my devices, but when I attempt to retrieve the info for them, I get the following error message.  This was encountered when I was trying to "Add Sensor".

Error while getting the devices of this jwt: Request failed with status code 403

**Comment by NeunLeben69** [comment]
How do you download? There is no instruction whatsoever.

**Comment by Loopher** [comment]
On the main page, there is a Releases 1 option.  Click on that and you will see the windows files there.

[Releases 1]   https://github.com/Sheherezadhe/awair-uploader/releases

**Comment by Sheherezadhe** [comment]
It is all explained in the reddit post:
https://www.reddit.com/r/PlanetWatchers/comments/tscbe3/project_awair_element_user_data_retrieval/

**Comment by NeunLeben69** [comment]
Not opening on Windows 11. It just downloaded a file named: <Unconfirmed 453641>

**Comment by shackrock** [comment]
My error after a restart and trying again...

![image](https://user-images.githubusercontent.com/559901/161356876-94e6ab2e-afcb-4d8f-9261-b30ce7150065.png)
