### ISSUE TITLE
Absolutely no instruction at all on how to download to PC

### ISSUE THREAD

**Issue by NeunLeben69** [Sheherezadhe/awair-uploader#15]
As if everyone knew how to use github! Poor job Plantewatch...

**Comment by Sheherezadhe** [comment]
It is all explained in the reddit post:
https://www.reddit.com/r/PlanetWatchers/comments/tscbe3/project_awair_element_user_data_retrieval/

**Comment by Dooooooood** [comment]
go to [https://github.com/Sheherezadhe/awair-uploader/releases](url)

**Comment by Dooooooood** [comment]
try https://github.com/Sheherezadhe/awair-uploader/releases
