### ISSUE TITLE
Only "Loading...." displayed on Mac

### ISSUE THREAD

**Issue by ignaciolarranaga** [Sheherezadhe/awair-uploader#18]
This is the screen I see:
<img width="1577" alt="Screen Shot 2022-04-01 at 20 56 01" src="https://user-images.githubusercontent.com/15932965/161355458-d5b7d7f8-ddf4-4bf0-963d-af5fcd105b41.png">

I cloned the repo and executed `npm install` and later `npm start`

I'm Intel (MacBook Pro 15-inch, 2018) with macOS Monterrey (version 12.2.1)

**Comment by Sheherezadhe** [comment]
It is all explained in the reddit post:
https://www.reddit.com/r/PlanetWatchers/comments/tscbe3/project_awair_element_user_data_retrieval/

**Comment by DrowningWhale** [comment]
Use the V1 release at https://github.com/Sheherezadhe/awair-uploader/releases

**Comment by ignaciolarranaga** [comment]
Thanks!
