### ISSUE TITLE
error installin g on a windows PC

### ISSUE THREAD

**Issue by Dekarikos** [Sheherezadhe/awair-uploader#38]
Hi girls and guys, 
I am very new to this here, but I am a planetWatcher and I have troublem installing the uploader on my WIN PC. I get this message. 
"There was an error while installing the application. Check the sutup log for more information and contact the author"
When I klick on "open Setup Log" nothing happens. 
Hope for help from some Planetwatcher, who alreasy installed it!
Thanks

**Comment by Warmduscher** [comment]
Most likely you try to install it on an older OS which is 32-Bit. The awair-uploader is only released for 64-bit.

**Comment by Dekarikos** [comment]
Hi Sheherazadhe,
Thanks for the info! I have an other PC that runs 64-bit! I’ll try that on this one! 
Thank you sooo much for doing all this. Helping the community of us Planetwatchers and simple people like me with support! 
Great Respekt! 


Von meinem iPhone gesendet

**Comment by Warmduscher** [comment]
If this works, you should close this issue to relieve some stress from the dev (which i am not btw)

**Comment by Dekarikos** [comment]
Hi Warmduscher, I think I got it! Thank you!
Sorry I thought you where Sheherazadhe! 
I'm so happy to be a part of this great Community!
Thanks again to the dev!
👍

**Comment by Dekarikos** [comment]
It works!
Thanks!


Am So., 3. Apr. 2022 um 12:32 Uhr schrieb Warmduscher <
***@***.***>:
