### ISSUE TITLE
Question: won’t awair block us

### ISSUE THREAD

**Issue by biohazd** [Sheherezadhe/awair-uploader#4]
If we all have a “pc” grabbing the awair data very often, won’t it mean Awair themselves will get swamped with requests and probably block us and planetwatch?

**Comment by Sheherezadhe** [comment]
Isn't the user entitled to the data from his device? I appreaciate the question but I would prefer chat to happen on my redditpost so I can filter. I want to work on solutions with people on github and not so much get into chat about hypotheticals, random questions, debates, arguments or things like that. Sorry I don't want to be rude but I have a lot things to do. I will come from time to time and try to answer such general questions in the subreddit. Please bear with me and also talk maybe about such things with the community.

**Comment by Sheherezadhe** [comment]
https://www.reddit.com/r/PlanetWatchers/comments/tscbe3/project_awair_element_user_data_retrieval/
