### ISSUE TITLE
15 minutes reporting loop

### ISSUE THREAD

**Issue by slobod1an** [Sheherezadhe/awair-uploader#42]
Hello, quick question about reporting loop, is there some kind of rate limits on PW side to prevent more frequent data delivery? with https://github.com/Sheherezadhe/awair-uploader/blob/main/src/constants.ts#L19 configuration were making 4 calls to PW API per hour, 96 per day, nothing close to 720 data/point...

**Comment by Sheherezadhe** [comment]
It is meant like that and will suffice for full rewards, simply to not congest and not pressure load
