### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by polde** [Sheherezadhe/awair-uploader#6]
Is it possible to run this on Raspberry Pi?

Thank you!

**Comment by Sheherezadhe** [comment]
Your question is already answered on the subreddit post. I appreaciate the question but I would prefer chat to happen on my redditpost so I can filter. I want to work on solutions with people on github and not so much get into chat about hypotheticals, random questions, debates, arguments or things like that. Sorry I don't want to be rude but I have a lot things to do. I will come from time to time and try to answer such general questions in the subreddit. Please bear with me and also talk maybe about such things with the community on the subreddit post.

**Comment by Sheherezadhe** [comment]
https://www.reddit.com/r/PlanetWatchers/comments/tscbe3/project_awair_element_user_data_retrieval/
