### ISSUE TITLE
Add sensor, returns an error

### ISSUE THREAD

**Issue by Jack4362** [Sheherezadhe/awair-uploader#7]
Error states, "Error while getting the devices of this jwt: Request failed with status code 403."
Unable to see any token, so can add token. 
![Capture](https://user-images.githubusercontent.com/102830026/161334172-003c365b-b9fc-4488-a226-b93e27faea2c.PNG)

**Comment by biohazd** [comment]
Do you have a local firewall blocking connections OUTBOUND?

**Comment by Jack4362** [comment]
No.  I figured it out.  I didn't read the instruction. And I didn't know I have to just back to my phone to use the Airwair App to get the token.  I thought there is a browser version of that app.  Now the "logs" state, it is retrieving data from my sensor.  We will see what happens.  Thanks for commenting.
