### ISSUE TITLE
On re-running Awair-uploader no login screen is displayed

### ISSUE THREAD

**Issue by PaulCP2410** [Sheherezadhe/awair-uploader#70]
I have had the uploader running successfully for over two days. Yesterday, I had to re-run it when it stopped sending data, and it worked ok after re-running it. Now after shutting it down, when I re-run awair-uploader, initial screen loads, message "Loading..." appears, and when I force reload, it responds with "Something went wrong". There is no login screen.
I have tried uninstalling and reinstalling the application from a fresh download, have shut down PC and restarted it. No luck.
Any ideas?

![Awair Uploader error](https://user-images.githubusercontent.com/103153741/162092572-2a42e49e-b09f-4849-b4e9-99b866d9a32e.png)

**Comment by Ryan-Goldstein** [comment]
PlanetWatch doesn't accept Awair streams anymore; it's no longer a supported device.

AMA including details here: https://www.youtube.com/watch?v=-t17AHt4mQw

**Comment by PaulCP2410** [comment]
Thanks Ryan
