### ISSUE TITLE
POST to https://wearableapi.planetwatch.io/api/data/devicedata returning a 301

### ISSUE THREAD

**Issue by tomatobrown** [Sheherezadhe/awair-uploader#71]
Seems like the endpoint for uploading the data may have changed, https://wearableapi.planetwatch.io/api/data/devicedata is returning a 301

**Comment by Ryan-Goldstein** [comment]
PlanetWatch doesn't accept Awair streams anymore; it's no longer a supported device.

AMA including details here: https://www.youtube.com/watch?v=-t17AHt4mQw

**Comment by tomatobrown** [comment]
bummer, thanks for the update
