### ISSUE TITLE
READ THIS

### ISSUE THREAD

**Issue by mdragosv** [Sheherezadhe/awair-uploader#73]
The tool is no longer working / supported by PlanetWatch.

Watch https://www.youtube.com/watch?v=-t17AHt4mQw

In short: 

The devices already registered with a license will receive 5.4 planets / day from PlanetWatch

The devices bought but not registered need to contact PlanetWatch support see the youtube special ama at https://www.youtube.com/watch?v=-t17AHt4mQw

**Comment by Francisx999** [comment]
I have having the same error message "Something Went Wrong"
